@echo off
echo Starting AutoATC Backend...
cd /d "%~dp0backend"
echo Installing minimal dependencies...
python -m pip install fastapi uvicorn pydantic-settings sqlalchemy python-multipart pillow
echo Starting FastAPI server...
python simple_main.py
pause
