@echo off
echo Starting AutoATC Frontend...
cd /d "%~dp0frontend\streamlit_app"
echo Installing dependencies...
python -m pip install -r requirements.txt
echo Starting Streamlit app...
streamlit run app.py
pause
